In [1]:
cd ..

/Users/satouwataru/Desktop/DiveIntoCode/git/diveintocode-ml/GraduationWork/v1/codes

In [2]:
cd ..

/Users/satouwataru/Desktop/DiveIntoCode/git/diveintocode-ml/GraduationWork/v1

In [3]:
import numpy as np
import pandas as pd

In [4]:
def preprocessing(yyyyMMdd):
    df = pd.read_csv('data/marge/marge.csv', index_col=0).reset_index(drop = True)
    M_TEAM_NAMES = pd.read_csv('data/other/TEAM_NAMES.csv').values.tolist()
    M_COACH_LIST = pd.read_csv('data/other/COACH_LIST.csv').columns.tolist()
    
    df = df[df['年月日'] < yyyyMMdd]
    df = df.reset_index(drop = True)
    
    # ○○、○○成功率　をまとめる
    h_a = ['H_', 'A_']
    par_calumns = ['パス', 'クロス', 'スローイン', 'ドリブル', 'タックル']
    for head in h_a:
        for col in par_calumns:
            df[head+'成功した'+col] = df[head + col] * df[head + col + '成功率']/100
            df[head+'失敗した'+col] = df[head + col] - df[head+'成功した'+col]
            df.drop(columns = [head + col], inplace = True)
            df.drop(columns = [head + col + '成功率'], inplace = True)
            
    hour_list = []
    for i, row in df.iterrows():
        hour_list += [row['キックオフ時刻'][:2]]
    df_tmp = pd.DataFrame(hour_list, columns = ['キックオフ時'])
    df = pd.concat([df, df_tmp],axis=1)
    df.drop(columns = ['キックオフ時刻'], inplace = True)
    
    hare_list, ame_list, kumori_list, okunai_list = [], [], [], []
    j1_list, j2_list, j3_list = [], [], []
    h_df_list, h_mf_list, h_fw_list = [], [], []
    a_df_list, a_mf_list, a_fw_list = [], [], []
    h_rank_list, a_rank_list = [], []
    for i, row in df.iterrows():
        whether = row['天候']
        category = row['カテゴリ']

        H_positions = ''
        A_positions = ''
        for i in range(1, 12):
            H_positions += row['H_ポジション' + str(i)]
            A_positions += row['A_ポジション' + str(i)]

        h_df_list += [H_positions.count('DF')]
        h_mf_list += [H_positions.count('MF')]
        h_fw_list += [H_positions.count('FW')]
        a_df_list += [A_positions.count('DF')]
        a_mf_list += [A_positions.count('MF')]
        a_fw_list += [A_positions.count('FW')]
        
        h_rank_list += [str(row['H_順位']).replace('※', '')]
        a_rank_list += [str(row['A_順位']).replace('※', '')]
        
        if category == 'J1':
            j1_list += [1]
            j2_list += [0]
            j3_list += [0]
        elif category == 'J2':
            j1_list += [0]
            j2_list += [1]
            j3_list += [0]
        else:
            j1_list += [0]
            j2_list += [0]
            j3_list += [1]

        if 0 < whether.count('晴'):
            hare_list += [1]
        else:
            hare_list += [0]
        if 0 < whether.count('雨'):
            ame_list += [1]
        else:
            ame_list += [0]
        if 0 < whether.count('曇'):
            kumori_list += [1]
        else:
            kumori_list += [0]
        if 0 < whether.count('室内'):
            okunai_list += [1]
        else:
            okunai_list += [0]

    df_tmp1 = pd.DataFrame(hare_list, columns = ['晴_flg'])
    df_tmp2 = pd.DataFrame(ame_list, columns = ['雨_flg'])
    df_tmp3 = pd.DataFrame(kumori_list, columns = ['曇_flg'])
    df_tmp4 = pd.DataFrame(okunai_list, columns = ['室内_flg'])
    df_tmp5 = pd.DataFrame(j1_list, columns = ['J1_flg'])
    df_tmp6 = pd.DataFrame(j2_list, columns = ['J2_flg'])
    df_tmp7 = pd.DataFrame(j3_list, columns = ['J3_flg'])
    df_tmp8 = pd.DataFrame(h_df_list, columns = ['H_DF'])
    df_tmp9 = pd.DataFrame(h_mf_list, columns = ['H_MF'])
    df_tmp10 = pd.DataFrame(h_fw_list, columns = ['H_FW'])
    df_tmp11 = pd.DataFrame(a_df_list, columns = ['A_DF'])
    df_tmp12 = pd.DataFrame(a_mf_list, columns = ['A_MF'])
    df_tmp13 = pd.DataFrame(a_fw_list, columns = ['A_FW'])
    df_tmp14 = pd.DataFrame(h_rank_list, columns = ['H_順位'])
    df_tmp15 = pd.DataFrame(a_rank_list, columns = ['A_順位'])
    
    
    df = pd.concat([df, df_tmp1, df_tmp2, df_tmp3, df_tmp4, df_tmp5, df_tmp6, df_tmp7, df_tmp8, df_tmp9, df_tmp10, df_tmp11, df_tmp12, df_tmp13, df_tmp14, df_tmp15],axis=1)

    drop_colmuns = []
    for i in range(1, 12):
        drop_colmuns += ['H_ポジション' + str(i)]
        drop_colmuns += ['A_ポジション' + str(i)]
        drop_colmuns += ['H_選手' + str(i)]
        drop_colmuns += ['A_選手' + str(i)]
        
    df = team_to_index(df)
    df = coach_to_index(df)
    
    df.drop(columns = ['天候', 'カテゴリ', 'H_順位', 'A_順位'] + drop_colmuns, inplace = True)
    df.drop(columns = ['スタジアム', '入場者数', '気温', '湿度', '晴_flg', '雨_flg', '曇_flg', '室内_flg'], inplace = True)
    df = df.astype('float64')
    
    df.to_csv("data/model/preprocessing_"+str(yyyyMMdd)+".csv")
    
    return df

In [5]:
def team_to_index(df):
    
    M_TEAM_NAMES = pd.read_csv('data/other/TEAM_NAMES.csv').values.tolist()
    
    df = df.copy()
    m_team_list = []
    for i, team_list in enumerate(M_TEAM_NAMES):
        m_team_list += [team_list[0]]

    h_team_list = []
    a_team_list = []
    for i, row in df.iterrows():
        h_team_list += [m_team_list.index(row['H_Team'])]
        a_team_list += [m_team_list.index(row['A_Team'])]
    df_tmp1 = pd.DataFrame(h_team_list, columns = ['H_Team'])
    df_tmp2 = pd.DataFrame(a_team_list, columns = ['A_Team'])
    df.drop(columns = ['H_Team', 'A_Team'], inplace=True)
    df = pd.concat([df, df_tmp1, df_tmp2], axis=1)
    
    return df

In [6]:
def coach_to_index(df):
    M_COACH_LIST = pd.read_csv('data/other/COACH_LIST.csv', index_col=0).reset_index(drop = True).T.values[0].tolist()
    
    for i, row in df.iterrows():
        try:
            M_COACH_LIST.index(row['H_監督'])
        except ValueError:
            M_COACH_LIST += [row['H_監督']]
        try:
            M_COACH_LIST.index(row['A_監督'])
        except ValueError:
            M_COACH_LIST += [row['A_監督']]
    df_corch = pd.DataFrame(M_COACH_LIST, columns = ['監督名'])
    df_corch.to_csv("data/other/COACH_LIST.csv")
    
    df = df.copy()
    h_coach_list = []
    a_coach_list = []
    for i, row in df.iterrows():
        h_coach_list += [M_COACH_LIST.index(row['H_監督'])]
        a_coach_list += [M_COACH_LIST.index(row['A_監督'])]
            
    df.drop(columns = ['H_監督', 'A_監督'], inplace=True)
    df_tmp1 = pd.DataFrame(h_coach_list, columns = ['H_監督'])
    df_tmp2 = pd.DataFrame(a_coach_list, columns = ['A_監督'])
    df = pd.concat([df, df_tmp1, df_tmp2], axis=1)
    
    return df

In [7]:
preprocessing(20150000)

/Users/satouwataru/.pyenv/versions/anaconda3-2020.07/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3357: DtypeWarning: Columns (13,24) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

,年月日,節,H_勝点,H_試合,H_勝,H_分,H_敗,H_得点,H_失点,H_得失点差,...,H_DF,H_MF,H_FW,A_DF,A_MF,A_FW,H_Team,A_Team,H_監督,A_監督
0,20141208.0,34.0,44.0,33.0,12.0,8.0,13.0,30.0,34.0,-4.0,...,4.0,4.0,2.0,4.0,4.0,2.0,32.0,4.0,29.0,44.0
1,20141206.0,34.0,47.0,33.0,12.0,11.0,10.0,42.0,37.0,5.0,...,3.0,6.0,1.0,4.0,4.0,2.0,15.0,1.0,144.0,75.0
2,20141206.0,34.0,60.0,33.0,18.0,6.0,9.0,64.0,38.0,26.0,...,4.0,5.0,1.0,4.0,4.0,2.0,2.0,18.0,178.0,146.0
3,20141206.0,34.0,32.0,33.0,8.0,8.0,17.0,42.0,60.0,-18.0,...,4.0,4.0,2.0,4.0,4.0,2.0,25.0,13.0,73.0,72.0
4,20141206.0,34.0,62.0,33.0,18.0,8.0,7.0,51.0,30.0,21.0,...,3.0,6.0,1.0,4.0,4.0,2.0,3.0,11.0,57.0,170.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2497,20120304.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,2.0,4.0,3.0,3.0,17.0,54.0,199.0,34.0
2498,20120304.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,4.0,3.0,4.0,4.0,2.0,9.0,35.0,93.0,9.0
2499,20120304.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,4.0,3.0,3.0,6.0,1.0,36.0,47.0,183.0,112.0
2500,20120304.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,5.0,2.0,4.0,4.0,2.0,39.0,16.0,108.0,25.0
2501,20120304.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,2.0,4.0,4.0,2.0,30.0,23.0,58.0,202.0